### ISSUE TITLE
Add language.

### ISSUE THREAD

**Issue by RemixerSV** [masagrator/AIR-ENX#1]
Hello. Could you please tell me how to extract files from a .nsz file. I want to add Russian language to this game. I tried to open .PCK files with some programs, but none of them will open the file.

**Comment by masagrator** [comment]
1. I am not helping with extracting nsz. I am using DBI to get files from installed games.
2. Nintendo Switch version of game doesn't use PCK files.

**Comment by RemixerSV** [comment]
Ah yes, files with a .PAK extension. Tried several programmes that are designed to open LucaSystem games.

**Comment by masagrator** [comment]
PAKs structure differs depending on what is actually there.
That's why I am using separate scripts for SCRIPT.PAK and PARTS.PAK

for anything else than SCRIPT.PAK use image_unpacker.py, but I don't give any warranty it's compatible with anything else than PARTS.PAK

This script is unpacking everything inside PAK that follows specific structure

**Comment by RemixerSV** [comment]
Can you share the scripts that can be used to extract and repack SCRIPT.PAK.

пн, 6 июн. 2022 г. в 20:28, MasaGratoR ***@***.***>:

**Comment by masagrator** [comment]
Everything is in repo...

script_disassemble.py is doing 2 in 1: unpacking and disassembling SCRIPT.PAK

**Comment by RemixerSV** [comment]
OK, I unpacked SCRIPT.PAK. The files that unzipped are in the .dat
extension. Is this correct? If so, how do I edit them?

пн, 6 июн. 2022 г. в 23:08, MasaGratoR ***@***.***>:

**Comment by masagrator** [comment]
You don't edit those.
You are editing files in "json" folder

**Comment by RemixerSV** [comment]
![2022-06-11_16-50-13](https://user-images.githubusercontent.com/100199919/173182910-d284ada2-56bb-4147-a516-67786fb15b51.png)
When I run Make_Script, this error appears.

**Comment by masagrator** [comment]
Ah, okay. Didn't force encoding for opened files, so for systems with different default encoding if Python couldn't detect encoding it will set wrong encoding. One moment

**Comment by masagrator** [comment]
Fixed it. I think it should work now 
download script_assemble.py from repo and replace it

**Comment by RemixerSV** [comment]
Thank you. You're really cool.
